### ISSUE TITLE
Uncaught ReferenceError: ngData is not defined

### ISSUE THREAD

**Issue by fdjean** [lykmapipo/ngData#5]
Hi,
ngdata.js:1224 Uncaught ReferenceError: ngData is not defined 

``` javascript
}());
return ngData; <--
}));
```

Grunt build it's ok: 
ngData/dist/ngdata.js 

Tx

**Comment by lykmapipo** [comment]
@fdjean 

Sorry ngData is `WIP`. I have to flag the project.

Sorry.

**Comment by fdjean** [comment]
ok ;)

**Comment by lykmapipo** [comment]
@fdjean 

We have release v0.1.0. Check in bower registry
